---
- name: Install nginx
  yum:
    name: nginx
    state: present
- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: nginx
- name: Enable service nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: true
