---
  - name: "Setup and install software for app server"
    hosts: localhost
    connection: local 
    tasks:
    - name: "Include server variables to server"
      include_vars: server_vars.yml
    - name: Install Apache
      yum:
        name: httpd
        state: present
      become: true
      when: metadata_server_type == "app"
    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        state: started
        name: httpd
      become: true
      when: metadata_server_type == "app"
    - name: Enable service httpd
      ansible.builtin.systemd:
        name: httpd
        enabled: true
      become: true
      when: metadata_server_type == "app"
  - name: "Setup and install software for web server"
    hosts: localhost
    connection: local 
    tasks:
    - name: "Include server variables"
      include_vars: server_vars.yml
    - name: Install nginx
      yum:
        name: nginx
        state: present
      become: true
      when: metadata_server_type == "web"
    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        state: started
        name: nginx
      become: true
      when: metadata_server_type == "web"
    - name: Enable service nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: true
      become: true
      when: metadata_server_type == "web"
