---
- hosts: localhost
  connection: local
  become: true
  include_vars: server_vars.yml
  roles:
    - httpd
      when: metadata_server_type == "app"
    - nginx
      when: metadata_server_type == "web"
